config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  resources :teachers
  resources :students
  resources :cohorts
  resources :courses
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
    has_many :students, :dependent => :nullify
    belongs_to :teacher
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :cohorts , dependent: :destroy
    validates :hours, numericality: { :greater_than => 0 } 
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :cohort
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_many :cohorts , :dependent => :nullify
    validates_inclusion_of :age, :in => 1..150
    validates :salary, numericality: { :greater_than => 0 }
     def concat_name
        "#{fname} #{lname}"
     end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    layout :layout_by_resource

    private
  
    def layout_by_resource
      if devise_controller?
        "devise"
      else
        "application"
      end
    end
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
    before_action :authenticate_admin!
    
    def index
        @cohorts = Cohort.order("id ASC")
        @teachers = Teacher.all
        @courses = Course.all
    end

    def show
        @cohort = Cohort.find(params[:id])
        @teachers = Teacher.all
        @students = Student.all
    end

    def new
        @cohort = Cohort.new
        @courses = Course.all
        @teachers = Teacher.all
        
    end
    
    def create
        @cohort = Cohort.create(cohort_params)
        redirect_to :controller => 'cohorts', :action => 'index'
    end

    def edit
        @cohort = Cohort.find(params[:id])
        @courses = Course.all
        @teachers = Teacher.all
    end
    def update
        @cohort = Cohort.find(params[:id])
        @cohort.update(cohort_params)
        redirect_to :controller => 'cohorts', :action => 'show'
    end

    def destroy
        @cohort = Cohort.find(params[:id])
        @cohort.destroy

        redirect_to :controller => 'cohorts', :action => 'index'
    end
end

private

def cohort_params
    params.require(:cohort).permit(:name,:start_date,:end_date,:teacher_id,:course_id)
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    before_action :authenticate_admin!
    def index
        @courses = Course.all
        
    end

    def show
       
        @course = Course.find(params[:id])
    end

    def new
        @course= Course.new
    end

    def create
        @course = Course.create(course_params)
        redirect_to :controller => 'courses', :action => 'index'
    end
    
    def edit
        @course = Course.find(params[:id])
    end

    def update
        @course = Course.find(params[:id])
        @course.update(course_params)
        redirect_to :controller => 'courses', :action => 'show'
    end
    
    def destroy
        @course = Course.find(params[:id])
        @course.destroy

        redirect_to :controller => 'courses', :action => 'index'
    end
 
end

private

def course_params
    params.require(:course).permit(:name,:hours,:pic_url)
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_action :authenticate_admin!

    def home
        @student = Student.count
        @course = Course.count
        @teacher= Teacher.count
        @cohort= Cohort.count
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    before_action :authenticate_admin!
    def index
        @students = Student.order("id ASC")
        
        @cohorts = Cohort.all
    end

    def show
        @student = Student.find(params[:id])
    end

    def new
        @student = Student.new
        @cohorts = Cohort.all
        
        
    end

    def create
        @student = Student.create(student_params)
        redirect_to :controller => 'students', :action => 'index'
    end

    def edit
        @student = Student.find(params[:id])
        @cohorts = Cohort.all
    end

    def update
        @student = Student.find(params[:id])
        @student.update(student_params)
        redirect_to :controller => 'students', :action => 'show'
    end

    def destroy
        @student = Student.find(params[:id])
        @student.destroy
        redirect_to :controller => 'students', :action => 'index'
    end
  
end


private

def student_params
    params.require(:student).permit(:fname,:lname,:age,:cohort_id,:phone_number,:email,:pic_url)
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
    before_action :authenticate_admin!
    def index
        @teachers = Teacher.all
        @cohorts = Cohort.all
    end

    def show
        @teacher = Teacher.find(params[:id])

    end

    def new
        @teacher = Teacher.new
    end

    def create
      @teacher = Teacher.create(teacher_params)

      redirect_to :controller => 'teachers', :action => 'index'

    end

    def edit
        @teacher = Teacher.find(params[:id])
    end


    def update
        @teacher = Teacher.find(params[:id])
        @teacher.update(teacher_params)
        redirect_to :controller => 'teachers', :action => 'show'
    end

    def destroy
        @teacher = Teacher.find(params[:id])
        @teacher.destroy
        redirect_to :controller => 'teachers', :action => 'index'
    end
end



private

def teacher_params
    params.require(:teacher).permit(:fname,:lname,:age,:salary,:education,:phone_number,:email,:pic_url)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cohorts/destroy.js.erb
console.log('Im in the destroy js file')
$('#cohort-<%= @cohort.id %>').fadeOut(300);

app/views/cohorts/edit.html.erb
<div class="div-inner">
<div class="title-div"><h3>Edit Cohort</h3></div>
<div class="table-div">
<div class="form-title-div"><h3>Cohort Details</h3></div>
<hr>


<%= form_with model: @cohort do |form| %>
  <div class="new-form-div">
  <div class="new-input-div"><div><p>Cohort Name</p></div><%= form.text_field :name %></div>

  <div class="form-inner">
    <div class="new-input-div"><div><p>Start Date</p></div><%= form.date_field :start_date %></div>
    <div class="new-input-div"><div><p>End Date</p></div><%= form.date_field :end_date %></div>
    </div>

    <%teacher_options = options_from_collection_for_select(@teachers,'id','concat_name')%>
    <div class="new-input-div"><div><p>Teacher ID</p></div><%= form.select :teacher_id,teacher_options %></div>
    <%options = options_from_collection_for_select(@courses,'id','name')%>
   <div class="new-input-div"><div><p>Course ID</p></div><%= form.select :course_id ,options%></div>
    <div class="new-submit"><%= form.submit %></div>
    </div>
  <% end %>

</div>
</div>
</div>

app/views/cohorts/index.html.erb
<div class="div-inner">
<div class="title-div"><h3>All Cohorts</h3></div>
<div class="table-div">

<div id="table-container">
<div class="add-div"><a class="add-cohort" href="/cohorts/new"><i class="fas fa-plus"></i>Add Cohort</a></div>
<table>
<tr>
<th>Id</th>
<th class="name-table">Name</th>
<th class="date-table">Start date</th>
<th class="date-table">End date</th>
<th class="instructor-table">Instructor</th>
<th class="course-table">Course</th>
<th>Edit</th>
</tr>
<% @cohorts.each do |cohort|%>
    <tr>
    <td><%=cohort.id%></td>
    <td class="name-table"><a href="/cohorts/<%=cohort.id%>"><%=cohort.name%></a></td>
    <td class="date-table"><%=cohort.start_date.strftime("%m/%d/%Y")%></td>
    <td class="date-table"><%=cohort.end_date.strftime("%m/%d/%Y")%></td>
    <% if cohort.teacher_id.nil?%>
    <td class="instructor-table">N/A</td>
    <%else%>
   <%current_teacher = @teachers.find(cohort.teacher_id)%>
   <td class="instructor-table"><a href="/teachers/<%=current_teacher.id%>"><%=current_teacher.fname%> <%=current_teacher.lname%></a></td>
   <%end%>
   <%current_course = @courses.find(cohort.course_id)%>
   <td class="course-table"><a href="/courses/<%=current_course.id%>"><%=current_course.name%></a></td>

   <td class="edit-row">
   <div><a href="/cohorts/<%=cohort.id%>/edit"><i id="edit-icon"class="far fa-edit"></i></a></div>
   <div class="trash-div"><%= link_to image_tag('trash-alt-regular.svg',:class => 'delete-btn'),cohort_path(cohort), method: :delete, remote:true, data: { confirm: 'Are you sure?' } %></div>
   </td>

   </tr>
   <% end %>
</table>

</div>
</div>
</div>

app/views/cohorts/new.html.erb
<div class="div-inner">
<div class="title-div"><h3>Add Cohort</h3></div>
<div class="table-div">
<div class="form-title-div"><h3>Cohort Details</h3></div>
<hr>

<%= form_with model: @cohort do |form| %>
  <div class="new-form-div">
  <div class="new-input-div"><div><p>Cohort Name</p></div><%= form.text_field :name%></div>

  <div class="form-inner">
  <div class="new-input-div"><div><p>Start Date</p></div> <%= form.date_field :start_date%></div>
  <div class="new-input-div"><div><p>End Date</p></div> <%= form.date_field :end_date %></div>
  </div>
  <%teacher_options = options_from_collection_for_select(@teachers,'id','concat_name')%>
  <div class="new-input-div"><div><p>Teacher ID</p></div><%= form.select :teacher_id,teacher_options %></div>

  <%options = options_from_collection_for_select(@courses,'id','name')%>
  <div class="new-input-div"><div><p>Course ID</p></div><%= form.select :course_id ,options%></div>
  <div class="new-submit"><%= form.submit %></div>
  </div>
<% end %>

</div>
</div>
</div>

app/views/cohorts/show.html.erb
<div class="div-inner">
<div class="title-div"><h3>Cohort Details</h3></div>

<div class="cohort-flex">

<div class ="cohort-table">

<div class="description-div">
<div class="cohort-name">
<h3> <%=@cohort.name %></h3>

<div class="cohort-edit-delete-div">
<div class="person-edit-icon"><a href="/cohorts/<%=@cohort.id%>/edit"><i class="far fa-edit"></i></a></div>
<div class="trash-div"><%= link_to image_tag('trash-alt-regular.svg',:class => 'delete-btn-student'),cohort_path(@cohort), method: :delete, remote:true, data: { confirm: 'Are you sure?' } %></div>
</div>
</div>






<div class="cohort-description">
<div><h3>Description</h3></div>
<% if @cohort.teacher_id.nil?%>
<div id="display-teacher"> <h4>Instructor </h4><p>TBD</p></div>
<%else%>

<% teacher_id = @cohort.teacher_id%>
<% current_teacher = @teachers.find(teacher_id) %>
<div id="display-teacher"> <h4>Instructor </h4> <p><%=current_teacher.fname%> <%=current_teacher.lname%></p></div>
<%end%>

<div><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p></div>
</div>

<div class="date-outer">
<h4>Duration</h4>
<div class="date-div">
<div><p>Start date <%=@cohort.start_date %></p></div>
<div><p>End date <%=@cohort.end_date %></p></div>
</div>
</div>

</div>
</div>


<div id="small">

<div id="student-heading"><h3>Students Enrolled</h3> <a href="/students/new"><i class="fas fa-plus"></i></a></div>


<div>
<table class="enrolled">

<tr>
<th></th>
<th>Name</th>
<th>Edit</th>
</tr>

<% id = @cohort.id%>
<% cohort_students = @students.where(cohort_id: id) %>
<% cohort_students.each do |student| %>


<tr>
<td class="hover-section"><a href="/students/<%=student.id%>"><img src="<%=student.pic_url%>"></a> </td>
<td><%= student.fname%> <%= student.lname%></td>
<td><div><a href="/students/<%=student.id%>/edit"><i class="far fa-edit"></i></a></div></td>
<%end%>
</tr>

</table>
</div>
</div>

</div>
</div>

app/views/courses/destroy.js.erb
console.log('Im in the destroy js file')
$('#course-<%= @course.id %>').fadeOut(300);

app/views/courses/edit.html.erb
<div class="div-inner">
<div class="title-div"><h3>Edit Course</h3></div>
<div class="table-div">
<div class="form-title-div"><h3>Course Details</h3></div>
<hr>


<%= form_with model: @course do |form| %>
  <div class="new-form-div">

  <div class="new-input-div"><div><p>Course Name</p></div><%= form.text_field :name, required: true%></div>
  <div class="new-input-div"><div><p>Course Hours</p></div><%= form.number_field :hours, min: 1, required: true%></div>
  <div class="new-input-div"><div><p>Picture</p></div><%= form.text_field :pic_url, required: true%></div>
  <div class="new-submit"><%= form.submit %></div>

  </div>
  <% end %>


  </div>
</div>
</div>

app/views/courses/index.html.erb
<div class="div-inner">
<div class="title-div"><h3>All Courses</h3></div>
<div class="table-div">



<div class="add-btn-div"><a class="add-cohort" href="/courses/new"><i class="fas fa-plus"></i>Add Course</a></div>

<div class="course-container">



<% @courses.each do |course|%>
    <div class="course-div">
    <div class="course-img-div"><a href="/courses/<%=course.id%>"><img src="<%=course.pic_url%>"></a></div>

    <div class="course-main-about">
    <div class="course-heading"><h3><%=course.name%></h3></div>
    <div><p>Hours: <%=course.hours%></p></div>
    <div class="read-div"><a class="read-more" href="/courses/<%=course.id%>">Read More</a></div>
   </div>

   </div>
<% end %>

</div>
</div>

</div>

</div>

</div>

app/views/courses/new.html.erb
  <div class="div-inner">
<div class="title-div"><h3>Add Course</h3></div>
<div class="table-div">
<div class="form-title-div"><h3>Course Details</h3></div>
<hr>


<%= form_with model: @course do |form| %>
  <div class="new-form-div">

  <div class="new-input-div"><div><p>Course Name</p></div><%= form.text_field :name,required: true %></div>
  <div class="new-input-div"><div><p>Course Hours</p></div><%= form.number_field :hours, min: 1, required: true%></div>
  <div class="new-input-div"><div><p>Picture</p></div><%= form.text_field :pic_url,required: true%></div>
  <div class="new-submit"><%= form.submit %></div>

  </div>
  <% end %>


  </div>
</div>
</div>

app/views/courses/show.html.erb
<div class="div-inner">
<div class="title-div"><h3>Course Details</h3></div>

<div class="flex">
<div class="small-table-div">

<div class="course-display">
<div class="course-img-div"><img src="<%=@course.pic_url%>"></div>
<div class="course-name"><%=@course.name%></div>
</div>
</div>


<div class="med-table-div">

<div class="description-div">
<div class="description-title">
<h3>Description</h3>
<div class="show-icons">
<div class="course-edit-icon"><a href="/courses/<%=@course.id%>/edit"><i class="far fa-edit"></i></a></div>
<div class="trash-div show"><%= link_to image_tag('trash-alt-regular.svg',:class => 'delete-btn'),course_path(@course), method: :delete, remote:true, data: { confirm: 'Are you sure?' } %></div>
</div>
</div>

<div><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p></div>

<div class="hours-id-div">
<div class="hours-div">
<div><h3>Course Hours</h3></div>
<div><p><%=@course.hours%></p></div>   
</div>

<div>
<div><h3>Course ID</h3></div>
<div><p><%=@course.id%></p></div>
</div>
</div>

</div>

</div>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NYCBA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
  </head>

  <body>

<div id="nav">
<div id="logo">
<h3><a class="nycba" href="/">NYCBA</a></h3>
</div>

<div id="icon">
<div><img src="http://i66.tinypic.com/50muex.png"></div>

<div id="dropdown">
<i class="fas fa-sort-down"></i>
 <div id="drop-content">
 <p><%= link_to "Log Out", destroy_admin_session_path, method: :delete %></p>
 </div>
</div>

</div>
</div>


<div id="sidenav">

<div id="icon-div">
<div><img src="http://i63.tinypic.com/2l5o1y.jpg"></div>
<p>Admin</p>
</div>

<div id="links">
<a href="/"><div>Dashboard<i class="fas fa-angle-right"></i></div></a>
<a href="/students"><div>Students<i class="fas fa-angle-right"></i></div></a>
<a href="/teachers"><div>Teachers<i class="fas fa-angle-right"></i></div></a>
<a href="/cohorts"><div>Cohort<i class="fas fa-angle-right"></i></div></a>
<a href="/courses"><div>Courses<i class="fas fa-angle-right"></i></div></a>

</div>

</div>



    <%= yield %>


  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>NYCBA</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body class="devise-body">

<div class="login-outer">
<h1 class="school-logo">NYCBA</h1>
<div class="input-area">
<div class="input-inner">
<%=yield%>
</div>
</div>


</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>NYCBA</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" type="text/css" media="screen" href="home.css" />
    
</head>
<body>


<div id="display-container">
<h2 id="dashboard">Dashboard</h2>

<div id="display-inner">

<a class="data-link" href="/students">
<div class="data-div">
<div><i class="fas fa-users"></i></div>
<div>
<h3>Total Students<h3>
<h4><%=@student%><h4>
</div>
</div>

<a class="data-link" href="/teachers">
<div class="data-div">
<div><i class="fas fa-chalkboard-teacher"></i></div>
<div>
<h3>Total Teachers<h3>
<h4><%=@teacher%><h4>
</div>
</div>
</a>

<a class="data-link" href="/courses">
<div class="data-div">
<div><i class="fas fa-graduation-cap"></i></div>
<div>
<h3>Courses<h3>
<h4><%=@course%><h4>
</div>
</div>
</a>

<a class="data-link" href="/cohorts">
<div class="data-div">
<div><i class="fas fa-book"></i></div>
<div>
<h3>Cohorts<h3>
<h4><%=@cohort%><h4>
</div>
</div>
</a>


</div>

</div>
<script src="main.js"></script>
</body>
</html>

app/views/students/destroy.js.erb
console.log('Im in the destroy js file')
$('#student-<%= @student.id %>').fadeOut(300);

app/views/students/edit.html.erb
<div class="div-inner">
<div class="title-div"><h3>Edit Student</h3></div>
<div class="table-div">
<div class="form-title-div"><h3>Student Details</h3></div>
<hr>



<%= form_with model: @student do |form| %>
  <div class="new-form-div">
  <div class="form-flex">
  <div class="form-inner">
  <div class="new-input-div"><div><p>First Name</p></div><%= form.text_field :fname,required: true %></div>
    <div class="new-input-div"><div><p>Age</p></div><%= form.number_field :age ,required: true%></div>
    <div class="new-input-div"><div><p>Phone Number</p></div><%= form.telephone_field :phone_number,required: true %></div>
    <div class="new-input-div"><div><p>Cohort Id</p></div><%= form.number_field :cohort_id %></div>
  </div>

  <div class="form-inner">
    <div class="new-input-div"><div><p>Last Name</p></div> <%= form.text_field :lname ,required: true%></div>
    <div class="new-input-div"><div><p>Email</p></div><%= form.email_field :email ,required: true%></div>
    <div class="new-input-div"><div><p>Picture</p></div><%= form.text_field :pic_url%></div>
    

  </div>
  </div>
    <div class="new-submit"><%= form.submit %></div>

  <% end %>
  

</div>
</div>
</div>

app/views/students/index.html.erb
<div class="div-inner">
<div class="title-div"><h3>All Students</h3></div>
<div class="table-div">

<div id="table-container">
<div class="add-div"><a class="add-cohort" href="/students/new"><i class="fas fa-plus"></i>Add Student</a></div>
<table class="display-students-table">
<tr>
<th></th>
<th>Id</th>
<th>Name</th>
<th>Age</th>
<th>Cohort</th>
<th>Edit</th>
</tr>
<% @students.each do |student|%>
    <tr>
    <td class="hover-section"><a href="/students/<%=student.id%>"><div><img src="<%=student.pic_url%>"></div></a> </td>
    <td><%=student.id%></td>
    <td><a href="students/<%=student.id%>"><%=student.fname%> <%=student.lname%></a></td>
    <td><%=student.age%></td>

    <% if student.cohort_id.nil?%>
    <td>N/A</td>
    <%else%>
    <td><a href="/cohorts/<%= @cohorts.find(student.cohort_id).id%>"> <%= @cohorts.find(student.cohort_id).name%></a></td>
    <%end%>
   <td>
   <div class="edit-section">
   <div><a class="edit-hover" href="/students/<%=student.id%>/edit"><i class="far fa-edit"></i></a></div>
   <div class="trash-div"><%= link_to image_tag('trash-alt-regular.svg',:class => 'delete-btn-student'),student_path(student), method: :delete, remote:true, data: { confirm: 'Are you sure?' } %></div>
   <div>
   </td>

   </tr>
   <% end %>
</table>

</div>
</div>
</div>

app/views/students/show.html.erb
<div class="div-inner">
<div class="title-div"><h3>Student Profile</h3></div>
<div id="profile-table-div" class="table-div">
<div class="edit-delete-div">
<div class="person-edit-icon"><a href="/students/<%=@student.id%>/edit"><i class="far fa-edit"></i></a></div>
<div class="trash-div"><%= link_to image_tag('trash-alt-regular.svg',:class => 'delete-btn-student'),student_path(@student), method: :delete, remote:true, data: { confirm: 'Are you sure?' } %></div>
</div>

<div class = "info-container">

<div class="profile-border">
<div class="profile-img-div"><img src="<%=@student.pic_url%>"></div>
</div>

<div class="display-info">

<div>
<div class="line">
<div class="bold">Full Name</div> <div class="info-font"><%=@student.fname %> <%=@student.lname %></div>
</div>

<div class="line">
<div class="bold">Email</div> <div class="info-font"><%=@student.email %> </div>
</div>

<div class="line">
<% if @student.cohort_id.nil?%>
<div class="bold">Cohort</div> <div class="info-font">N/A</div>
    <%else%>
<div class="bold">Cohort</div> <div class="info-font"><%=@student.cohort_id %></div>
<%end%>
</div>

</div>



<div>

<div class="line">
<div class="bold">Phone Number</div> <div class="info-font"><%=number_to_phone(@student.phone_number) %></div>
</div>

<div class="line">
<div class="bold">Age</div>  <div class="info-font"><%=@student.age %></div>
</div>

</div>



</div>
</div>

</div>
</div>

app/views/teachers/destroy.js.erb
console.log('Im in the destroy js file')
$('#teachers-<%= @teacher.id %>').fadeOut(300);

app/views/teachers/show.html.erb
<div class="div-inner">
<div class="title-div"><h3>Teacher Profile</h3></div>
<div id="teacher-table-div" class="table-div">

<div class="edit-delete-div">
<div class="person-edit-icon"><a href="/teachers/<%=@teacher.id%>/edit"><i class="far fa-edit"></i></a></div>
<div class="trash-div"><%= link_to image_tag('trash-alt-regular.svg',:class => 'delete-btn-student'),teacher_path(@teacher), method: :delete, remote:true, data: { confirm: 'Are you sure?' } %></div>
</div>

<div class = "info-container">
<div class="profile-border">
<div class="profile-img-div"><img src="<%=@teacher.pic_url%>"></div>
</div>

<div class="display-info">

<div>
<div class="line">
<div class="bold">Full Name</div> <div class="info-font"><%=@teacher.fname %> <%=@teacher.lname %></div>
</div>

<div class="line">
<div class="bold">Salary</div> <div class="info-font"><%=number_to_currency(@teacher.salary)%> </div>
</div>

<div class="line">
<div class="bold">Email</div> <div class="info-font"><%=@teacher.email %> </div>
</div>
</div>



<div>
<div class="line">
<div class="bold">Age</div>  <div class="info-font"><%=@teacher.age %></div>
</div>

<div class="line">
<div class="bold">Education</div> <div class="info-font"><%=@teacher.education %> </div>
</div>

<div class="line">
<div class="bold">Phone Number</div> <div class="info-font"><%=number_to_phone(@teacher.phone_number) %></div>
</div>

<div class="line">
<div class="bold">ID Number</div> <div class="info-font"><%=@teacher.id%></div>
</div>

</div>


</div>
</div>



</div>
</div>